-- ============================================================
-- 멀티테넌트 마이그레이션 스크립트
-- 실행 순서대로 진행하세요
-- ============================================================

-- ============================================================
-- STEP 1: 회사 테이블 생성
-- ============================================================

-- 회사 시퀀스
CREATE SEQUENCE COMPANIES_SEQ START WITH 1 INCREMENT BY 1;

-- 회사 테이블
CREATE TABLE COMPANIES (
    ID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    BUSINESS_NUMBER VARCHAR2(20),
    REPRESENTATIVE VARCHAR2(50),
    PHONE VARCHAR2(20),
    EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(300),
    LOGO_URL VARCHAR2(500),
    THEME_COLOR VARCHAR2(20),
    CONTACT_EMAIL VARCHAR2(100),
    CONTACT_PHONE VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    PLAN_TYPE VARCHAR2(20) DEFAULT 'BASIC' NOT NULL,
    MAX_USERS NUMBER DEFAULT 10,
    MAX_WAREHOUSES NUMBER DEFAULT 5,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CHK_COMPANY_STATUS CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'DELETED')),
    CONSTRAINT CHK_COMPANY_PLAN CHECK (PLAN_TYPE IN ('BASIC', 'STANDARD', 'PREMIUM', 'ENTERPRISE'))
);

-- 인덱스
CREATE INDEX IDX_COMPANY_STATUS ON COMPANIES(STATUS);
CREATE INDEX IDX_COMPANY_NAME ON COMPANIES(NAME);

-- 코멘트
COMMENT ON TABLE COMPANIES IS '회사 (테넌트) 정보';
COMMENT ON COLUMN COMPANIES.ID IS '회사 고유 ID';
COMMENT ON COLUMN COMPANIES.NAME IS '회사명';
COMMENT ON COLUMN COMPANIES.BUSINESS_NUMBER IS '사업자등록번호';
COMMENT ON COLUMN COMPANIES.REPRESENTATIVE IS '대표자명';
COMMENT ON COLUMN COMPANIES.PHONE IS '대표 연락처';
COMMENT ON COLUMN COMPANIES.EMAIL IS '대표 이메일';
COMMENT ON COLUMN COMPANIES.ADDRESS IS '주소';
COMMENT ON COLUMN COMPANIES.LOGO_URL IS '로고 이미지 URL';
COMMENT ON COLUMN COMPANIES.THEME_COLOR IS '테마 색상 (HEX)';
COMMENT ON COLUMN COMPANIES.CONTACT_EMAIL IS '고객지원 이메일';
COMMENT ON COLUMN COMPANIES.CONTACT_PHONE IS '고객지원 전화번호';
COMMENT ON COLUMN COMPANIES.STATUS IS '상태 (ACTIVE/SUSPENDED/DELETED)';
COMMENT ON COLUMN COMPANIES.PLAN_TYPE IS '요금제 (BASIC/STANDARD/PREMIUM/ENTERPRISE)';
COMMENT ON COLUMN COMPANIES.MAX_USERS IS '최대 사용자 수';
COMMENT ON COLUMN COMPANIES.MAX_WAREHOUSES IS '최대 창고 수';

-- ============================================================
-- STEP 2: 기본 회사 생성 (LS Mecapion)
-- 기존 데이터를 이 회사에 할당합니다
-- ============================================================

INSERT INTO COMPANIES (ID, NAME, BUSINESS_NUMBER, STATUS, PLAN_TYPE, MAX_USERS, MAX_WAREHOUSES)
VALUES ('LSMECA', 'LS Mecapion', NULL, 'ACTIVE', 'ENTERPRISE', 100, 20);

COMMIT;

-- ============================================================
-- STEP 3: 기존 테이블에 COMPANY_ID 컬럼 추가 (NULL 허용)
-- 기존 시스템이 계속 작동하도록 NULL 허용
-- ============================================================

-- 사용자 테이블
ALTER TABLE LS_USERS ADD COMPANY_ID VARCHAR2(20);

-- 창고 테이블
ALTER TABLE LS_WAREHOUSES ADD COMPANY_ID VARCHAR2(20);

-- 재고 마스터 테이블
ALTER TABLE LS_MOTOR_RACK ADD COMPANY_ID VARCHAR2(20);

-- 수불 이력 테이블
ALTER TABLE LS_MOTOR_SUBUL ADD COMPANY_ID VARCHAR2(20);

-- 품목 마스터 테이블
ALTER TABLE LS_MOTOR_ITEM ADD COMPANY_ID VARCHAR2(20);

-- ============================================================
-- STEP 4: 기존 데이터에 기본 회사 ID 할당
-- ============================================================

UPDATE LS_USERS SET COMPANY_ID = 'LSMECA' WHERE COMPANY_ID IS NULL;
UPDATE LS_WAREHOUSES SET COMPANY_ID = 'LSMECA' WHERE COMPANY_ID IS NULL;
UPDATE LS_MOTOR_RACK SET COMPANY_ID = 'LSMECA' WHERE COMPANY_ID IS NULL;
UPDATE LS_MOTOR_SUBUL SET COMPANY_ID = 'LSMECA' WHERE COMPANY_ID IS NULL;
UPDATE LS_MOTOR_ITEM SET COMPANY_ID = 'LSMECA' WHERE COMPANY_ID IS NULL;

COMMIT;

-- ============================================================
-- STEP 5: 인덱스 추가 (회사별 조회 최적화)
-- ============================================================

-- 사용자 테이블 인덱스
CREATE INDEX IDX_USERS_COMPANY ON LS_USERS(COMPANY_ID);

-- 창고 테이블 인덱스
CREATE INDEX IDX_WAREHOUSES_COMPANY ON LS_WAREHOUSES(COMPANY_ID);

-- 재고 마스터 인덱스
CREATE INDEX IDX_RACK_COMPANY ON LS_MOTOR_RACK(COMPANY_ID);
CREATE INDEX IDX_RACK_COMPANY_STORAGE ON LS_MOTOR_RACK(COMPANY_ID, STORAGE);
CREATE INDEX IDX_RACK_COMPANY_ITEM ON LS_MOTOR_RACK(COMPANY_ID, ITEM_CODE);
CREATE INDEX IDX_RACK_COMPANY_LOCATION ON LS_MOTOR_RACK(COMPANY_ID, LOCATION);

-- 수불 이력 인덱스
CREATE INDEX IDX_SUBUL_COMPANY ON LS_MOTOR_SUBUL(COMPANY_ID);
CREATE INDEX IDX_SUBUL_COMPANY_TIME ON LS_MOTOR_SUBUL(COMPANY_ID, SUBUL_TIME DESC);

-- 품목 마스터 인덱스
CREATE INDEX IDX_ITEM_COMPANY ON LS_MOTOR_ITEM(COMPANY_ID);
CREATE INDEX IDX_ITEM_COMPANY_CODE ON LS_MOTOR_ITEM(COMPANY_ID, ITEM_CODE);

-- ============================================================
-- STEP 6: 외래키 추가 (선택사항 - 데이터 무결성)
-- 주의: 기존 데이터가 모두 마이그레이션된 후 실행
-- ============================================================

-- 외래키는 일단 주석 처리 (필요시 활성화)
-- ALTER TABLE LS_USERS ADD CONSTRAINT FK_USERS_COMPANY
--     FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID);

-- ALTER TABLE LS_WAREHOUSES ADD CONSTRAINT FK_WAREHOUSES_COMPANY
--     FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID);

-- ALTER TABLE LS_MOTOR_RACK ADD CONSTRAINT FK_RACK_COMPANY
--     FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID);

-- ALTER TABLE LS_MOTOR_SUBUL ADD CONSTRAINT FK_SUBUL_COMPANY
--     FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID);

-- ALTER TABLE LS_MOTOR_ITEM ADD CONSTRAINT FK_ITEM_COMPANY
--     FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES(ID);

-- ============================================================
-- STEP 7: NOT NULL 제약조건 추가 (완전 전환 후)
-- 주의: 모든 데이터가 마이그레이션되고 코드가 완전히 전환된 후 실행
-- ============================================================

-- NOT NULL 제약조건은 일단 주석 처리 (Phase 3에서 활성화)
-- ALTER TABLE LS_USERS MODIFY COMPANY_ID NOT NULL;
-- ALTER TABLE LS_WAREHOUSES MODIFY COMPANY_ID NOT NULL;
-- ALTER TABLE LS_MOTOR_RACK MODIFY COMPANY_ID NOT NULL;
-- ALTER TABLE LS_MOTOR_SUBUL MODIFY COMPANY_ID NOT NULL;
-- ALTER TABLE LS_MOTOR_ITEM MODIFY COMPANY_ID NOT NULL;

-- ============================================================
-- 검증 쿼리
-- ============================================================

-- 회사 확인
SELECT * FROM COMPANIES;

-- 각 테이블 COMPANY_ID 할당 확인
SELECT 'LS_USERS' AS TABLE_NAME, COUNT(*) AS TOTAL,
       SUM(CASE WHEN COMPANY_ID IS NOT NULL THEN 1 ELSE 0 END) AS WITH_COMPANY
FROM LS_USERS
UNION ALL
SELECT 'LS_WAREHOUSES', COUNT(*), SUM(CASE WHEN COMPANY_ID IS NOT NULL THEN 1 ELSE 0 END)
FROM LS_WAREHOUSES
UNION ALL
SELECT 'LS_MOTOR_RACK', COUNT(*), SUM(CASE WHEN COMPANY_ID IS NOT NULL THEN 1 ELSE 0 END)
FROM LS_MOTOR_RACK
UNION ALL
SELECT 'LS_MOTOR_SUBUL', COUNT(*), SUM(CASE WHEN COMPANY_ID IS NOT NULL THEN 1 ELSE 0 END)
FROM LS_MOTOR_SUBUL
UNION ALL
SELECT 'LS_MOTOR_ITEM', COUNT(*), SUM(CASE WHEN COMPANY_ID IS NOT NULL THEN 1 ELSE 0 END)
FROM LS_MOTOR_ITEM;
