-- ============================================================
-- LS Motor 재고관리 시스템 - Oracle DDL
-- ============================================================

-- 시퀀스 생성
CREATE SEQUENCE LS_MOTOR_RACK_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LS_MOTOR_SUBUL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LS_MOTOR_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LS_USERS_SEQ START WITH 1 INCREMENT BY 1;

-- ============================================================
-- 0. 회원 테이블 (ls_users)
-- ============================================================
CREATE TABLE LS_USERS (
    ID NUMBER DEFAULT LS_USERS_SEQ.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(200) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    APPROVED_AT TIMESTAMP,
    APPROVED_BY NUMBER,
    CONSTRAINT CHK_USER_STATUS CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT CHK_USER_ROLE CHECK (ROLE IN ('USER', 'ADMIN'))
);

-- 인덱스
CREATE INDEX IDX_USER_EMAIL ON LS_USERS(EMAIL);
CREATE INDEX IDX_USER_STATUS ON LS_USERS(STATUS);

COMMENT ON TABLE LS_USERS IS '회원 정보';
COMMENT ON COLUMN LS_USERS.ID IS '회원 ID';
COMMENT ON COLUMN LS_USERS.NAME IS '회원 이름';
COMMENT ON COLUMN LS_USERS.EMAIL IS '이메일 (로그인 ID)';
COMMENT ON COLUMN LS_USERS.PASSWORD IS '비밀번호 (해시)';
COMMENT ON COLUMN LS_USERS.STATUS IS '상태 (PENDING: 승인대기, APPROVED: 승인됨, REJECTED: 거절됨)';
COMMENT ON COLUMN LS_USERS.ROLE IS '역할 (USER: 일반, ADMIN: 관리자)';
COMMENT ON COLUMN LS_USERS.CREATED_AT IS '가입일시';
COMMENT ON COLUMN LS_USERS.APPROVED_AT IS '승인일시';
COMMENT ON COLUMN LS_USERS.APPROVED_BY IS '승인자 ID';

-- 관리자 계정 (비밀번호: admin123 - 실제 운영시 변경 필요)
-- 비밀번호는 bcrypt 해시로 저장됨
INSERT INTO LS_USERS (NAME, EMAIL, PASSWORD, STATUS, ROLE)
VALUES ('관리자', 'admin@lsmecapion.com', '$2b$10$zkUDk29iHQ0neLn9dehqzulJpjg/fFjXSNf7WW4vqlqP1ZgkQZo/u', 'APPROVED', 'ADMIN');

-- ============================================================
-- 1. 재고 마스터 테이블 (ls_motor_rack)
-- ============================================================
CREATE TABLE LS_MOTOR_RACK (
    ID NUMBER DEFAULT LS_MOTOR_RACK_SEQ.NEXTVAL PRIMARY KEY,
    STORAGE VARCHAR2(50) NOT NULL,
    LOCATION VARCHAR2(50) NOT NULL,
    ITEM_CODE VARCHAR2(100) NOT NULL,
    ITEM_NAME VARCHAR2(200) NOT NULL,
    NOW_QTY NUMBER DEFAULT 0 NOT NULL,
    IN_DAY TIMESTAMP,
    REMARK VARCHAR2(500)
);

-- 인덱스
CREATE INDEX IDX_RACK_STORAGE ON LS_MOTOR_RACK(STORAGE);
CREATE INDEX IDX_RACK_LOCATION ON LS_MOTOR_RACK(LOCATION);
CREATE INDEX IDX_RACK_ITEM_CODE ON LS_MOTOR_RACK(ITEM_CODE);
CREATE INDEX IDX_RACK_ITEM_NAME ON LS_MOTOR_RACK(ITEM_NAME);

COMMENT ON TABLE LS_MOTOR_RACK IS '재고 마스터';
COMMENT ON COLUMN LS_MOTOR_RACK.ID IS '재고 ID';
COMMENT ON COLUMN LS_MOTOR_RACK.STORAGE IS '창고 번호';
COMMENT ON COLUMN LS_MOTOR_RACK.LOCATION IS '위치 (예: A-01-01)';
COMMENT ON COLUMN LS_MOTOR_RACK.ITEM_CODE IS '품목 코드';
COMMENT ON COLUMN LS_MOTOR_RACK.ITEM_NAME IS '품목명';
COMMENT ON COLUMN LS_MOTOR_RACK.NOW_QTY IS '현재 수량';
COMMENT ON COLUMN LS_MOTOR_RACK.IN_DAY IS '입고일';
COMMENT ON COLUMN LS_MOTOR_RACK.REMARK IS '비고';

-- ============================================================
-- 2. 수불 이력 테이블 (ls_motor_subul)
-- ============================================================
CREATE TABLE LS_MOTOR_SUBUL (
    ID NUMBER DEFAULT LS_MOTOR_SUBUL_SEQ.NEXTVAL PRIMARY KEY,
    STORAGE VARCHAR2(50) NOT NULL,
    LOCATION VARCHAR2(50) NOT NULL,
    ITEM_CODE VARCHAR2(100) NOT NULL,
    ITEM_NAME VARCHAR2(200) NOT NULL,
    QTY NUMBER DEFAULT 0 NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL,
    SUBUL_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    REMARK VARCHAR2(500),
    USER_ID VARCHAR2(100) DEFAULT 'system' NOT NULL
);

-- 인덱스
CREATE INDEX IDX_SUBUL_STORAGE ON LS_MOTOR_SUBUL(STORAGE);
CREATE INDEX IDX_SUBUL_LOCATION ON LS_MOTOR_SUBUL(LOCATION);
CREATE INDEX IDX_SUBUL_ITEM_CODE ON LS_MOTOR_SUBUL(ITEM_CODE);
CREATE INDEX IDX_SUBUL_CATEGORY ON LS_MOTOR_SUBUL(CATEGORY);
CREATE INDEX IDX_SUBUL_TIME ON LS_MOTOR_SUBUL(SUBUL_TIME DESC);

COMMENT ON TABLE LS_MOTOR_SUBUL IS '수불 이력';
COMMENT ON COLUMN LS_MOTOR_SUBUL.ID IS '이력 ID';
COMMENT ON COLUMN LS_MOTOR_SUBUL.STORAGE IS '창고 번호';
COMMENT ON COLUMN LS_MOTOR_SUBUL.LOCATION IS '위치';
COMMENT ON COLUMN LS_MOTOR_SUBUL.ITEM_CODE IS '품목 코드';
COMMENT ON COLUMN LS_MOTOR_SUBUL.ITEM_NAME IS '품목명';
COMMENT ON COLUMN LS_MOTOR_SUBUL.QTY IS '거래 수량';
COMMENT ON COLUMN LS_MOTOR_SUBUL.CATEGORY IS '거래 분류 (입고/출고/이동(출)/이동(입)/수정)';
COMMENT ON COLUMN LS_MOTOR_SUBUL.SUBUL_TIME IS '거래 시간';
COMMENT ON COLUMN LS_MOTOR_SUBUL.REMARK IS '비고';
COMMENT ON COLUMN LS_MOTOR_SUBUL.USER_ID IS '처리자';

-- ============================================================
-- 3. 품목 마스터 테이블 (ls_motor_item)
-- ============================================================
CREATE TABLE LS_MOTOR_ITEM (
    IDX NUMBER DEFAULT LS_MOTOR_ITEM_SEQ.NEXTVAL PRIMARY KEY,
    STORAGE VARCHAR2(50) NOT NULL,
    ITEM_CODE VARCHAR2(100) NOT NULL,
    ITEM_NAME VARCHAR2(200) NOT NULL,
    ERP_RESERVATION NUMBER DEFAULT 0,
    ERP_INVENTORY10 NUMBER DEFAULT 0,
    ERP_INVENTORY11 NUMBER DEFAULT 0,
    SHORTAGE NUMBER DEFAULT 0
);

-- 인덱스
CREATE INDEX IDX_ITEM_STORAGE ON LS_MOTOR_ITEM(STORAGE);
CREATE INDEX IDX_ITEM_CODE ON LS_MOTOR_ITEM(ITEM_CODE);
CREATE INDEX IDX_ITEM_NAME ON LS_MOTOR_ITEM(ITEM_NAME);

COMMENT ON TABLE LS_MOTOR_ITEM IS '품목 마스터';
COMMENT ON COLUMN LS_MOTOR_ITEM.IDX IS '품목 IDX';
COMMENT ON COLUMN LS_MOTOR_ITEM.STORAGE IS '기본 창고';
COMMENT ON COLUMN LS_MOTOR_ITEM.ITEM_CODE IS '품목 코드';
COMMENT ON COLUMN LS_MOTOR_ITEM.ITEM_NAME IS '품목명';
COMMENT ON COLUMN LS_MOTOR_ITEM.ERP_RESERVATION IS 'ERP 예약 수량';
COMMENT ON COLUMN LS_MOTOR_ITEM.ERP_INVENTORY10 IS 'ERP 재고 (창고10)';
COMMENT ON COLUMN LS_MOTOR_ITEM.ERP_INVENTORY11 IS 'ERP 재고 (창고11)';
COMMENT ON COLUMN LS_MOTOR_ITEM.SHORTAGE IS '부족 수량';

-- ============================================================
-- 샘플 데이터 (선택사항)
-- ============================================================

-- 품목 마스터 샘플
INSERT INTO LS_MOTOR_ITEM (STORAGE, ITEM_CODE, ITEM_NAME, ERP_RESERVATION, ERP_INVENTORY10, ERP_INVENTORY11, SHORTAGE) VALUES ('1', 'APM-SA01ACN', 'AC서보드라이버 L7SA 100W', 0, 50, 30, 0);
INSERT INTO LS_MOTOR_ITEM (STORAGE, ITEM_CODE, ITEM_NAME, ERP_RESERVATION, ERP_INVENTORY10, ERP_INVENTORY11, SHORTAGE) VALUES ('1', 'APM-SA02ACN', 'AC서보드라이버 L7SA 200W', 0, 40, 25, 0);
INSERT INTO LS_MOTOR_ITEM (STORAGE, ITEM_CODE, ITEM_NAME, ERP_RESERVATION, ERP_INVENTORY10, ERP_INVENTORY11, SHORTAGE) VALUES ('1', 'APM-SA04ACN', 'AC서보드라이버 L7SA 400W', 0, 35, 20, 0);
INSERT INTO LS_MOTOR_ITEM (STORAGE, ITEM_CODE, ITEM_NAME, ERP_RESERVATION, ERP_INVENTORY10, ERP_INVENTORY11, SHORTAGE) VALUES ('1', 'APM-SC01ANN', 'AC서보모터 100W', 0, 60, 40, 0);
INSERT INTO LS_MOTOR_ITEM (STORAGE, ITEM_CODE, ITEM_NAME, ERP_RESERVATION, ERP_INVENTORY10, ERP_INVENTORY11, SHORTAGE) VALUES ('1', 'APM-SC02ANN', 'AC서보모터 200W', 0, 55, 35, 0);

-- 재고 샘플
INSERT INTO LS_MOTOR_RACK (STORAGE, LOCATION, ITEM_CODE, ITEM_NAME, NOW_QTY, IN_DAY, REMARK) VALUES ('1', 'A-01-01', 'APM-SA01ACN', 'AC서보드라이버 L7SA 100W', 10, SYSDATE, NULL);
INSERT INTO LS_MOTOR_RACK (STORAGE, LOCATION, ITEM_CODE, ITEM_NAME, NOW_QTY, IN_DAY, REMARK) VALUES ('1', 'A-01-02', 'APM-SA02ACN', 'AC서보드라이버 L7SA 200W', 8, SYSDATE, NULL);
INSERT INTO LS_MOTOR_RACK (STORAGE, LOCATION, ITEM_CODE, ITEM_NAME, NOW_QTY, IN_DAY, REMARK) VALUES ('1', 'A-02-01', 'APM-SA04ACN', 'AC서보드라이버 L7SA 400W', 5, SYSDATE, NULL);
INSERT INTO LS_MOTOR_RACK (STORAGE, LOCATION, ITEM_CODE, ITEM_NAME, NOW_QTY, IN_DAY, REMARK) VALUES ('2', 'B-01-01', 'APM-SC01ANN', 'AC서보모터 100W', 15, SYSDATE, NULL);
INSERT INTO LS_MOTOR_RACK (STORAGE, LOCATION, ITEM_CODE, ITEM_NAME, NOW_QTY, IN_DAY, REMARK) VALUES ('2', 'B-01-02', 'APM-SC02ANN', 'AC서보모터 200W', 12, SYSDATE, NULL);

COMMIT;
